name: iox-parquet CI

on: 
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Build with Gradle (SNAPSHOT)
        id: buildSnapshotLib
        run: ./gradlew clean build sourcesJar javadocJar 

      - name: Build with Gradle (RELEASE)
        if: ${{ success() && github.ref == 'refs/heads/stable'}}
        id: buildReleaseLib
        run: ./gradlew clean build sourcesJar javadocJar -Drelease= 

      - name: Debug 1
        run: |
          ls -la build/libs

      - uses: actions/upload-artifact@v4
        if: always() && (steps.buildSnapshotLib.outcome == 'failure' && steps.buildReleaseLib.outcome == 'failure')
        with:
          name: reports
          path: build/reports/tests/

      - name: Decode
        if: always() && (steps.buildSnapshotLib.outcome == 'success' || steps.buildReleaseLiboutcome == 'success')
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > ~/.gradle/sonatype_upload.gpg.b64
          base64 -d ~/.gradle/sonatype_upload.gpg.b64 > ~/.gradle/sonatype_upload.gpg

      - name: Publish library jar file (SNAPSHOT)
        if: ${{ success() && (github.ref == 'refs/heads/main')}}
        run: ./gradlew -i publishToSonatype closeAndReleaseSonatypeStagingRepository -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gradle/sonatype_upload.gpg)
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}} 

      - name: Publish library jar file (RELEASE)
        if: ${{ success() && (github.ref == 'refs/heads/stable')}}
        run: ./gradlew -i publishToSonatype closeAndReleaseSonatypeStagingRepository -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gradle/sonatype_upload.gpg) -Drelease=
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}} 

      - name: Release library (RELEASE)
        if: ${{ success() && github.ref == 'refs/heads/stable'}}
        run: |
          ./gradlew -i app:jreleaserRelease -Drelease=
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
